name: ci
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache docker layers
      uses: actions/cache@v4
      with:
        path: /tmp2/.buildx-cache
        key: ${{ runner.os}}-buildx-${{ github.sha }}
        restore-keys: |
          ${{runner.os }}-buildx-
    
    - name: Build and push docker image
      uses: docker/build-push-action@v6
      with:
        file: ../.devcontainer/Dockerfile
        platforms: linux/amd64,linux/arm64
        pull: true
        push: true
        tags: ci:latest
        cache-to: type=local,dest=/tmp2/.buildx-cache,mode=max
        cache-from: type=local,src=/tmp2/.buildx-cache
    
    - name: Run tests
      run: echo "Running tests"
