name: ci
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Cpp
      uses: aminya/setup-cpp@v1
      with:
        compiler: llvm
        cmake: true

    - name: Create a symlink to cmake
      run: |
        mkdir -p /opt/cmake/bin
        ln -s /home/runner/cmake/cmake-3.30.4-linux-x86_64/bin/cmake /opt/cmake/bin/cmake

    - name: Build and Test
      run: |
        cmake -Bbuild -DTESTS=ON
        make -C build
        ctest --test-dir build