name: ci
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Cpp
      uses: aminya/setup-cpp@v1
      with:
        compiler: llvm
        cmake: true

    - name: Build and Test
      run: |
        cmake -Bbuild